### PR TITLE
List channels alphabetically

### PR DESCRIPTION
**Pull request by sander1**

### CODE REVIEW

**Comment by phrawzty** [comment]
This is obviously a good idea and I'm sort of embarrassed that I haven't already done it - I guess I just got used to things being in a non-deterministic order. :laughing: 

Thanks!

**Comment by sander1** [comment]
Haha, well I started using the channel a couple of days ago and found the "random" ordering quite annoying as I couldn't quickly find some of my favourite channels :) Thanks for pulling this in!

**Comment by phrawzty** [comment]
Mind if I ask how you found the channel? I'm curious how people come across
it. ☺

**Comment by sander1** [comment]
I just started a new premium account with DI.fm, but found out that their iOS app doesn't support Chromecast yet. Then I remembered that -a long time ago- I did a very small edit on a channel that supported DI.fm (https://github.com/phrawzty/AudioAddict.bundle/commit/8eac2c2204ba051e87bcc3df59109bd5842378f2) and then I found the source from your channel in Github again.

**Pull request merged**
